### ISSUE TITLE
isFunction

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-hooks-utils#37]
### `isFunction`

Checks if the provided value is a function.

`src/utils/type/isFunction.ts`

**Parameters**:
- `value: any`: The value to check.

**Returns**:
- `boolean`: Returns `true` if the value is a function, otherwise returns `false`.

**Example**:
```ts
isFunction(() => {});  // true
isFunction(function() {}); // true
isFunction(123);        // false
isFunction('Hello');    // false
isFunction(null);       // false

**Comment by doosabhulaxmi** [comment]
@bharat-dussa hi i want to solve this issue please assign

**Comment by RahulJOD** [comment]
Hi, Please assign this issue to me. I want to contribute.

**Comment by bharat-dussa** [comment]
Duplicate issuess
