### ISSUE TITLE
Testing using API's

### ISSUE THREAD

**Issue by bharat-dussa** [vituarvom/react-hooks-utils#39]
### `deepMerge`

Merges two objects deeply, including nested objects.

**File**: `src/utils/object/deepMerge.ts`

**Parameters**:
- `obj1: object`: The first object.
- `obj2: object`: The second object.

**Returns**:
- `object`: The merged object.

**Example**:
```ts
deepMerge({ a: 1, b: { c: 2 } }, { b: { d: 3 } });  // { a: 1, b: { c: 2, d: 3 } }
```

**Comment by vigneshbirru** [comment]
i love to contribute on this issue

**Comment by VamshiAdep** [comment]
@bharat-dussa i love to contribute to this task pls do need full

**Comment by bharat-dussa** [comment]
This is testig putpose only closing this
